export { HeroSection } from './Hero'
export { ProductDescriptionSection } from './ProductDescription'
export { NewslleterSection } from './Newslleter'
export { FeatureDemoSection } from './FeatureDemo'
export { PrinciplesSection } from './Principles'
export { ComingSoonSection } from './ComingSoon'
export { FooterSection } from './Footer'